import { useEffect, useRef, useState } from 'react'
import { Card, Stack, Typography, IconButton } from '@mui/material'
import PlayArrowIcon from '@mui/icons-material/PlayArrow'
import PauseIcon from '@mui/icons-material/Pause'
import ReplayIcon from '@mui/icons-material/Replay'

export default function Player({ audioUrl, onEdit, controlsDisabled }) {
  const audioRef = useRef(null)
  const [isPlaying, setIsPlaying] = useState(false)
  const [bars, setBars] = useState(() => new Array(12).fill(6))

  // UI-only equalizer animation
  useEffect(() => {
    let raf
    const tick = () => {
      setBars(prev =>
        prev.map((h, i) => {
          const variance = (Math.sin((Date.now() / 120) + i) + 1) * 0.5
          const target = 8 + Math.round(variance * 28)
          return Math.round(h + (target - h) * 0.25)
        })
      )
      raf = requestAnimationFrame(tick)
    }
    if (isPlaying) raf = requestAnimationFrame(tick)
    return () => { if (raf) cancelAnimationFrame(raf) }
  }, [isPlaying])

  useEffect(() => { // reset when new audio arrives
    setIsPlaying(false)
    const a = audioRef.current
    if (a) { a.pause(); a.currentTime = 0 }
  }, [audioUrl])

  const handlePlayPause = () => {
    const a = audioRef.current
    if (!a) return
    if (isPlaying) { a.pause(); setIsPlaying(false) }
    else { a.play(); setIsPlaying(true) }
  }
  const handleReplay = () => {
    const a = audioRef.current
    if (!a) return
    a.currentTime = 0
    a.play()
    setIsPlaying(true)
  }

  return (
    <Card sx={{ p: 4, textAlign: 'center' }} className="panel story-panel enter-bottom">
      <Stack spacing={2} alignItems="center" className="stack-fill">
        <Typography variant="h5">Story Player</Typography>

        {/* Equalizer – UI-only animation; runs only when isPlaying === true */}
        <div className="equalizer" style={{ opacity: isPlaying ? 1 : 0.25 }}>
          {bars.map((h, i) => (<div key={i} className="bar" style={{ height: h }} />))}
        </div>

        <audio ref={audioRef} src={audioUrl || ''} preload="auto" onEnded={() => setIsPlaying(false)} />

        <Stack direction="row" spacing={2} justifyContent="center" alignItems="center">
          <IconButton color="primary" size="large" onClick={handlePlayPause} aria-label="playpause" disabled={!audioUrl || controlsDisabled}>
            {isPlaying ? <PauseIcon fontSize="inherit" /> : <PlayArrowIcon fontSize="inherit" />}
          </IconButton>
          <IconButton color="primary" size="large" onClick={handleReplay} aria-label="replay" disabled={!audioUrl || controlsDisabled}>
            <ReplayIcon fontSize="inherit" />
          </IconButton>
        </Stack>

        <Stack direction={{ xs: 'column', sm: 'row' }} spacing={2} sx={{ mt: 2 }}>
          {/* Edit button only; Generate moved to the global switch */}
          <button
            className="btn btn-warning"
            onClick={() => {
              const a = audioRef.current
              if (a && !a.paused) { a.pause(); setIsPlaying(false) }
              onEdit && onEdit()
            }}
          >
            Edit
          </button>
        </Stack>

        <Typography variant="caption" sx={{ opacity: 0.7 }}>
          Audio generated by gTTS.
        </Typography>
      </Stack>
    </Card>
  )
}
